[package]
name = "studious-system"
version = "0.1.0"
edition = "2021"
authors = [
    "Martin Skatvedt"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.29.1"
gl = "0.14.0"
nalgebra-glm = "0.18.0"
libc = "0.2.144"
